---
- hosts: all
  become: true
  tasks:
    - name: installation d'un serveur apache
      command: yum -y install httpd
    - name:
      command: systemctl start httpd
    - name:
      command: systemctl enable httpd
    - name:
      command: yum -y install epel-release
    - name:
      command: rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
    - name:
      command: yum -y install mod_php72w php72w-cli php72w-common php72w-devel php72w-pear php72w-gd php72w-mbstring php72w-mysql php72w-xml php72w-bcmath
    - name:
      command: yum -y install vim
    - name:
      command: vim /etc/php.ini
## max_execution_time = 600
  # max_input_time = 600
  # memory_limit = 256M
  # post_max_size = 32M
  # upload_max_filesize = 16M
  # date.timezone = Europe/Paris

    - name:
      command: systemctl restart httpd
    - name:
      command: yum -y install mariadb-server
    - name:
      command: systemctl start mariadb
    - name:
      command: systemctl enable mariadb
    - name:
      command: mysql_secure_installation
    - name:
      command: mysql -u root -p
##create database zabbix;
  #grant all privileges on zabbix.* to zabbix@'localhost' identified by 'astondevops';
  #grant all privileges on zabbix.* to zabbix@'%' identified by 'astondevops';
  #flush privileges;


    - name:
      command: yum -y install http://repo.zabbix.com/zabbix/3.4/rhel/7/x86_64/zabbix-release-3.4-1.el7.centos.noarch.rpm
    - name:
      command: yum -y install zabbix-get zabbix-server-mysql zabbix-web-mysql zabbix-agent
    - name:
      command: cd /usr/share/doc/zabbix-server-mysql-3.4.9
    - name:
      command: gunzip create.sql.gz
    - name:
      command: mysql -u root -p zabbix < create.sql
    - name:
      command: vim etc/zabbix/zabbix_server.conf
##mdp:astondevops
    - name:
      command: systemctl start zabbix-server
    - name:
      command: systemctl status zabbix-server.service
    - name:
      command: setenforce Permissive
    - name:
      command: systemctl start zabbix-server
    - name:
      command: systemctl enable zabbix-server
    - name:
      command: systemctl restart zabbix-server
    - name:
      command: systemctl restart zabbix-agent
    - name:
      command: systemctl restart httpd

